[UVI-3965] Support multiple topics in spring-boot-starter-liiklus
UvitaTeam/spring-boot-starter-liiklus pull request #28
Opened 2020-02-10 15:05 UTC by umutuzgur

2020-02-10 15:26 UTC, bbednarek reviewed
@umutuzgur very nice job! 👏

2020-02-10 15:26 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +                            consumerProperties.getGroupVersion(), consumer);
move `consumer` to new line

2020-02-10 15:26 UTC, bbednarek commented on starter/src/test/java/io/vivy/liiklus/single/PartitionAwareConnectTest.java
> +                "test.groupName=p${random.uuid}-artitionaware",
typo

2020-02-10 15:46 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/publisher/LiiklusPublisher.java
> +    protected LiiklusClient liiklusClient;
can we make it `private final`?

2020-02-10 15:46 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/publisher/LiiklusPublisher.java
> +    protected String topic;
same here

2020-02-10 15:46 UTC, bbednarek commented on starter/src/test/java/io/vivy/liiklus/single/AbstractIntegrationTest.java
> -package io.vivy.liiklus;
rename the class to `SingleTopicTest`

2020-02-10 15:46 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerProperties.java
> +    String topic;
pls add validation

2020-02-10 15:46 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/publisher/LiiklusPublisherProperties.java
> +    String topic;
pls add validation

2020-02-10 16:34 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerLoop.java
> +        if (Objects.isNull(disposable)) {
please avoid this kind of changes and revert this one. Its out of scope and arguable making things better

2020-02-11 00:25 UTC, lanwen commented on README.md
> +implement `io.vivy.liiklus.consumer.RecordProcessor`
this is already in the name, also it would require migration, please keep it where it is right now

2020-02-11 00:26 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +        var readScheduler = Schedulers.newParallel("liiklus");
why?

2020-02-11 08:53 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +        var readScheduler = Schedulers.newParallel("liiklus");
Why for what? Could you care to elaborate? This is really not a helpful comment

2020-02-11 08:53 UTC, umutuzgur commented on README.md
> +implement `io.vivy.liiklus.consumer.RecordProcessor`
Sorry, intellij refactoring kicked in for this. I will cleanup the readme

2020-02-11 08:54 UTC, umutuzgur commented on starter/src/test/java/io/vivy/liiklus/single/PartitionAwareConnectTest.java
> +                "test.groupName=p${random.uuid}-artitionaware",
I did it like this on purpose 😝

2020-02-11 10:39 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerProperties.java
> +    String topic;
I'm already doing `environment.getRequiredProperty(prefix + ".topic")` which should check throw an exception if the value is null. Which case would you like me to validate further?

2020-02-11 10:39 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/publisher/LiiklusPublisherProperties.java
> +    String topic;
Same question as above

2020-02-11 10:41 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/publisher/LiiklusPublisher.java
> +    protected LiiklusClient liiklusClient;
I can't make it final since it is assigned when the init method is invoked but I can make it private

2020-02-11 10:57 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerLoop.java
> +        if (Objects.isNull(disposable)) {
reverted it

2020-02-11 12:07 UTC, bbednarek commented on README.md
> +implement `io.vivy.liiklus.consumer.RecordProcessor`
@lanwen I think we should decouple consumer and producer module completely to two different gradle modules
Keeping both of them in the same module is confusing. @umutuzgur moved them to two different packages for now and I think this will be first step before creating separated modules.

Once multiple topic support will be released, you will need to do significant changes in all of the project once we will release stable version. For now we will play around with it in crm service and once we are happy with this solution we will release official version.

2020-02-11 12:11 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerProperties.java
> +    String topic;
if it's blank we should fail for example

2020-02-11 12:11 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerProperties.java
> +    int groupVersion;
`@Min(1)`

2020-02-11 12:11 UTC, bbednarek commented on starter/src/main/java/io/vivy/liiklus/publisher/LiiklusPublisherProperties.java
> +    String topic;
`@NotBlank`

2020-02-11 12:46 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +        var readScheduler = Schedulers.newParallel("liiklus");
why did you extract a scheduler and why its parallel

2020-02-11 12:52 UTC, lanwen commented on README.md
> +implement `io.vivy.liiklus.consumer.RecordProcessor`
why its confusing? Just configuration should be clear. And that's not that much code to split it. You will end up with a more overhead that you want to solve. I don't think that moving to a separate packages producer and consumer is a nesessary change for the multiple topic feature. So please do it either separately, or don't do it at all.

I completely disagree about significant changes required - we should make it the way no significant changes should be required, otherwise we would end up in an infinite loop of refactorings. More than that, multiple topics actually could be handled with existing approach with just different microservices consuming different topic separately, but updating the same database.

2020-02-11 12:54 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +                    var consumerLoop = liiklusComponentFactory.createConsumer(
don't hide type if it couldn't be easility identified from the context.

2020-02-11 12:54 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +                            consumer);
codestyle: `)` should be on next line

2020-02-11 12:58 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +        var readScheduler = Schedulers.newParallel("liiklus");
It was previously paralle https://github.com/VivyTeam/spring-boot-starter-liiklus/blob/master/starter/src/main/java/io/vivy/liiklus/LiiklusConsumerLoop.java#L65 and I removed it so it can be used by multiple topic consumers

2020-02-12 10:12 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +        var readScheduler = Schedulers.newParallel("liiklus");
The whole thing is done to be safe in case someone would block the thread during processing. Thus now you have a danger that one consumer can now block all, I'd prefer to keep it independent

2020-02-12 10:23 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerProperties.java
> +        var topic = environment.getRequiredProperty(prefix + ".topic");
you could delegate this validation to spring if design props a bit different -
```
liiklus.topic.<topic>.version
liiklus.topic.<topic>.groupName
```

then you could read `liiklus.topic` to a map of topic -> ConsumerProps, then just put annotations and iterate the map

2020-02-12 10:27 UTC, lanwen requested changes
please keep the binary compatibility as much as possible,
otherwise we would take a week to just refactor our repos.
Then liiklus will implement cloud events spec and that would take us one more week.
And then we would change auth for liiklus to be async and tls and that would take us one more week. Thats too much.

Also props design could be simplified. Since we're using annotation based config, its weird to check props manually

Will check presisely more things during the day, but things above are no go for me in this PR

2020-02-13 09:08 UTC, umutuzgur commented
@lanwen I kept the backwards compatibility, moved to topics prefix to `liiklus.topics` and I'm now creating new schedulers for each LiiklusConsumerLoop so they don't block each other

2020-02-13 14:33 UTC, lanwen commented on starter/src/test/java/io/vivy/liiklus/multiple/MultipleTopicTest.java
> +                "liiklus.topics.user.topic=user-event-log",
you didn't get. it should no be this line

it should be only 
```
                "liiklus.topics.user-event-log.groupName=service1",
                "liiklus.topics.user-event-log.groupVersion=1",
                "liiklus.topics.global-event-log.groupName=service2",
                "liiklus.topics.global-event-log.groupVersion=3",
```

2020-02-13 14:39 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/producer/LiiklusProducer.java
> +    public void init(LiiklusClient liiklusClient, String topic) {
why its not a constructor?

2020-02-13 14:40 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerLoop.java
> +        if (Objects.nonNull(disposable)) {
why did you start doing this?

2020-02-13 14:41 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerLoop.java
> +                .subscribeOn(readScheduler)
please inline scheduler

2020-02-13 14:43 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerProperties.java
> +    public static LiiklusConsumerProperties create(LiiklusProperties properties, String name) {
why do you still creating it manually and not via spring?

2020-02-13 15:00 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/producer/LiiklusProducer.java
> +    public void init(LiiklusClient liiklusClient, String topic) {
ok, now I got the idea

2020-02-13 15:27 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumer.java
> +    protected LiiklusConsumerLoop consumerLoop;
what I didn't get in the api design is why do you need consumer loop here

2020-02-13 15:37 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusComponentFactory.java
> +package io.vivy.liiklus;
could be in the consumer package

2020-02-13 15:41 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +    public LiiklusComponentFactory liiklusComponentFactory(LiiklusClient liiklusClient) {
why do you need it as bean? It could be created right before the consumers

2020-02-13 15:45 UTC, lanwen commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +    @ConditionalOnProperty(prefix = "liiklus", name = {"topic", "groupName"})
could you please explain why do you need a property matching if we already have partiton aware dependency?

2020-02-13 21:00 UTC, lanwen commented on starter/src/test/java/io/vivy/liiklus/multiple/GlobalTopicConfiguration.java
> +    @Bean(destroyMethod = "close")
if you implement Autoclosable interface, you don't need to specify destroy method

2020-02-17 08:36 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerLoop.java
> +        if (Objects.nonNull(disposable)) {
I'm a big fan of this normally

2020-02-17 08:46 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +    @ConditionalOnProperty(prefix = "liiklus", name = {"topic", "groupName"})
I just wanted to be uniform with the LiiklusPublisher. I need this in LiiklusPublisher and since they are connected, it makes sense for me that they have this property

2020-02-17 08:49 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/LiiklusAutoConfiguration.java
> +    public LiiklusComponentFactory liiklusComponentFactory(LiiklusClient liiklusClient) {
I can do that as well. It was more of a design decision I made at the beginning

2020-02-17 08:49 UTC, umutuzgur commented on starter/src/test/java/io/vivy/liiklus/multiple/GlobalTopicConfiguration.java
> +    @Bean(destroyMethod = "close")
Thanks! Good to know that

2020-02-17 08:52 UTC, umutuzgur commented on starter/src/test/java/io/vivy/liiklus/multiple/MultipleTopicTest.java
> +                "liiklus.topics.user.topic=user-event-log",
I don't like this that much since in the future we can have only publishers and no consumers. Then, we would only need the topic but then the property parsing would be weird

2020-02-17 08:55 UTC, umutuzgur commented on starter/src/main/java/io/vivy/liiklus/consumer/LiiklusConsumerLoop.java
> +                .subscribeOn(readScheduler)
What do you mean by inlining it, like `.subscribeOn().subscribe();`?

2020-02-17 10:28 UTC, lanwen commented
okay, after some thoughts I agree with the configuration approach of naming things explicitly and assign topic and everything in config

I really like the api here 
http://smallrye.io/smallrye-reactive-messaging/#_reactive_streams_reactive_stream_operators_rx_java

so we could go into that direction
also maybe we could reuse something from the spring
https://docs.spring.io/spring-cloud-stream/docs/current/reference/htmlsingle/#_quick_start

2020-03-05 13:26 UTC, lanwen commented
Hey, @umutuzgur are you up to finishing some leftovers?

2020-03-11 14:39 UTC, lanwen approved these changes
Okay, so lets try this one as PoC and improve the api/implementation separately

2020-03-11 14:40 UTC, merged